### ISSUE TITLE
"image" in OneShotLabeller.py

### ISSUE THREAD

**Issue by cghAndy** [RBC-DSAI-IITM/SSCCNN#1]
```
new_Xmax = min(rightbottom_pixel[0], image.shape[1] - 1)
new_Ymax = min(rightbottom_pixel[1], image.shape[0] - 1)
```

what's the image in OneShotLabeller.py line 74 and 75?

**Comment by JoeHRIsaac** [comment]
The code makes a minimum enclosing circle of the points of the hand and those lines make a bounding box from it checking if it reaches beyond the edges of the frame
