### ISSUE TITLE
where is the code for the corrector module

### ISSUE THREAD

**Issue by cghAndy** [RBC-DSAI-IITM/SSCCNN#2]
The paper 4.1.1 Corrector Module Construction said "The code for the corrector module is publicly available", could you please let me know which part of the code is this module?
And which part of code I can study with if I want to take the hand poses of the current state-of-the-art models as input and correct the anatomical errors of the model?
Thanks.

**Comment by cghAndy** [comment]
Could you please provide me an example of the application of the corrector module ? like , the code using to correct A2J ?

**Comment by JoeHRIsaac** [comment]
Correction module is added in utils.py
Usage
`
corrected_pose, error = correctionModule(hand_pose, alpha_value)
`
Where alpha ranges from 0 to 1.0 as per paper and the hand_pose must be in the order as per HANDS2017 dataset (21x3 matrix). This call should be looped for every hand pose for A2J.
